name: Frontend Docker Build and Push

on:
  push:
    branches: [ "main", "master" ]  # Trigger on push to main or master branches
    paths:
      - "frontend/msti-automation/**"    # Trigger only if files under frontend/ changed

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (builder)
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend/msti-automation  # Path to context in frontend/
          file: ./frontend/msti-automation/Dockerfile   # Path to Dockerfile in frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest

